media:
  input: public/assets
  output: /assets

content:
  - name: posts
    label: 博客文章 (Posts)
    type: collection
    path: src/content/posts
    fields:
      - name: title
        label: 文章标题
        type: string
        required: true
      - name: description
        label: 文章简介
        type: string
        required: true
      - name: pubDatetime
        label: 发布日期
        type: datetime
        required: true
      - name: modDatetime
        label: 修改日期
        type: datetime
      - name: tags
        label: 标签
        type: list
        default: []
        items:
          type: string
      - name: draft
        label: 是否为草稿
        type: boolean
        default: false
      - name: body
        label: 正文内容
        type: rich-text